version: '3'

services:
  postgres:
    image: postgres:10.7-alpine
    restart: always
    environment:
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: user
          POSTGRES_DB: example
    ports:
      - 8091:5432

  spring-app:
    build: ./
    ports:
      - 8090:8090